import "~/styles/globals.css";
import TopNav from "./TopNav";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ConvexClientProvider } from "../provider/AuthProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col">
        <ConvexClientProvider>
          <TopNav />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
